### ISSUE TITLE
Client dosn't handle failover is primary is killed

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#239]
Reproducing this on localhost with 1 controllers and 2 shard servers with a simple single-threaded client.

**Comment by agazso** [comment]
This happened because #245: the client received a config state that had a quorum, which had an inactive primaryID and because quorum primaryID is in the volatile part of the config state. The changes in volatile part does not increment the config paxosID, so the client stuck. There was an optimization in the client that it watched the changes of paxosID, this is now removed. Also see #247
